## En este file juntaremos los 3 archivos y realizaremos en EDA

In [1]:
import pandas as pd
import numpy as np

Cargaremos el dataset steam_games

In [23]:
df_steam_games = pd.read_csv('steam.csv')

In [24]:
df_steam_games.head(4)

,publisher,genres,app_name,release_date,tags,specs,price,item_id,developer
0,Poolians.com,"['Casual', 'Free to Play', 'Indie', 'Simulatio...",Real Pool 3D - Poolians,2017-07-24,"['Free to Play', 'Simulation', 'Sports', 'Casu...","['Single-player', 'Multi-player', 'Online Mult...",0.00,670290.0,Poolians.com
1,彼岸领域,"['Action', 'Adventure', 'Casual']",弹炸人2222,2017-12-07,"['Action', 'Adventure', 'Casual']",['Single-player'],0.99,767400.0,彼岸领域
2,NaN,NaN,Log Challenge,NaN,"['Action', 'Indie', 'Casual', 'Sports']","['Single-player', 'Full controller support', '...",2.99,773570.0,NaN
3,Trickjump Games Ltd,"['Action', 'Adventure', 'Simulation']",Battle Royale Trainer,2018-01-04,"['Action', 'Adventure', 'Simulation', 'FPS', '...","['Single-player', 'Steam Achievements']",3.99,772540.0,Trickjump Games Ltd

In [25]:
df_steam_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32133 entries, 0 to 32132
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24062 non-null  object
 1   genres        28850 non-null  object
 2   app_name      32131 non-null  object
 3   release_date  30066 non-null  object
 4   tags          31970 non-null  object
 5   specs         31463 non-null  object
 6   price         32133 non-null  float64
 7   item_id       32131 non-null  float64
 8   developer     28834 non-null  object
dtypes: float64(2), object(7)
memory usage: 2.2+ MB

La columna item_id tiene un dato nulo, para poder trasformarla int, sustituiremos ese valor nulo por 0

In [26]:
# Llenar los valores nulos en 'item_id' con 0
df_steam_games['item_id'].fillna(0, inplace=True)

# Cambiaremos el tipo de dato
df_steam_games['item_id'] = df_steam_games['item_id'].astype(int)

Cargaremos el dataset user_items

In [27]:
df_user_items = pd.read_parquet('user_items.parquet')

In [28]:
# Mostramos información sobre el Dataframe
df_user_items

,index,user_id,item_id,item_name,playtime_forever
0,0,76561197970982479,10,Counter-Strike,0.1
1,0,76561197970982479,30,Day of Defeat,0.1
2,0,76561197970982479,300,Day of Defeat: Source,78.9
3,0,76561197970982479,240,Counter-Strike: Source,30.9
4,0,76561197970982479,3830,Psychonauts,5.6
...,...,...,...,...,...
3285241,88308,76561198329548331,304930,Unturned,11.3
3285242,88308,76561198329548331,227940,Heroes & Generals,0.7
3285243,88308,76561198329548331,388490,One Way To Die: Steam Edition,0.0
3285244,88308,76561198329548331,521570,You Have 10 Seconds 2,0.1
3285245,88308,76561198329548331,519140,Minds Eyes,0.0

Eliminamos la columna index

In [29]:
df_user_items = df_user_items.drop('index', axis=1)
df_user_items

,user_id,item_id,item_name,playtime_forever
0,76561197970982479,10,Counter-Strike,0.1
1,76561197970982479,30,Day of Defeat,0.1
2,76561197970982479,300,Day of Defeat: Source,78.9
3,76561197970982479,240,Counter-Strike: Source,30.9
4,76561197970982479,3830,Psychonauts,5.6
...,...,...,...,...
3285241,76561198329548331,304930,Unturned,11.3
3285242,76561198329548331,227940,Heroes & Generals,0.7
3285243,76561198329548331,388490,One Way To Die: Steam Edition,0.0
3285244,76561198329548331,521570,You Have 10 Seconds 2,0.1
3285245,76561198329548331,519140,Minds Eyes,0.0

In [30]:
df_user_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3285246 entries, 0 to 3285245
Data columns (total 4 columns):
 #   Column            Dtype
---  ------            -----
 0   user_id           object
 1   item_id           object
 2   item_name         object
 3   playtime_forever  float64
dtypes: float64(1), object(3)
memory usage: 100.3+ MB

Cargaremos el dataset user_reviews

In [31]:
df_user_reviews = pd.read_parquet('user_reviews.parquet')

Mostramos parte del Dataframe

In [34]:
df_user_reviews

                 user_id  recommend  sentiment_analysis  year
0      76561197970982479       True                   2  2011
1      76561197970982479       True                   2  2011
2      76561197970982479       True                   2  2011
3                js41637       True                   2  2014
4                js41637       True                   2  2013
...                  ...        ...                 ...   ...
59300  76561198312638244       True                   2     0
59301  76561198312638244       True                   2     0
59302        LydiaMorley       True                   2     0
59303        LydiaMorley       True                   2     0
59304        LydiaMorley       True                   2     0

[59305 rows x 4 columns]

Uniremos los Dataframes df_user_reviews y df_user_items mediante un merge para el cual utilizaremos el item_id del Dataframe df_user_items, procederemos a eliminar item_id de df_user_reviews.

In [33]:
# Eliminar la columna 'item_id'
df_user_reviews = df_user_reviews.drop('item_id', axis=1)

Mostramos parte del Dataframe

In [35]:
df_user_reviews

                 user_id  recommend  sentiment_analysis  year
0      76561197970982479       True                   2  2011
1      76561197970982479       True                   2  2011
2      76561197970982479       True                   2  2011
3                js41637       True                   2  2014
4                js41637       True                   2  2013
...                  ...        ...                 ...   ...
59300  76561198312638244       True                   2     0
59301  76561198312638244       True                   2     0
59302        LydiaMorley       True                   2     0
59303        LydiaMorley       True                   2     0
59304        LydiaMorley       True                   2     0

[59305 rows x 4 columns]

Mostramos información sobre df_user_reviews

In [36]:
df_user_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59305 entries, 0 to 59304
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             59305 non-null  object
 1   recommend           59305 non-null  bool
 2   sentiment_analysis  59305 non-null  int64
 3   year                59305 non-null  int64
dtypes: bool(1), int64(2), object(1)
memory usage: 1.4+ MB

Aplicaremos un inner merge entre los Dataframes df_user_items y df_user_reviews, se escogio usar el método inner para mantener la coincidencia entre ambas tablas mediante el campo user_id.

In [37]:
merged_items_reviews = pd.merge(left=df_user_items, right=df_user_reviews, on='user_id', how='inner')

mostramos información sobre merged_items_reviews

In [38]:
merged_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4956176 entries, 0 to 4956175
Data columns (total 7 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   item_id             object
 2   item_name           object
 3   playtime_forever    float64
 4   recommend           bool
 5   sentiment_analysis  int64
 6   year                int64
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 231.6+ MB

Mostramos parte del Dataframe

In [39]:
merged_items_reviews.head(5)

,user_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis,year
0,76561197970982479,10,Counter-Strike,0.1,True,2,2011
1,76561197970982479,10,Counter-Strike,0.1,True,2,2011
2,76561197970982479,10,Counter-Strike,0.1,True,2,2011
3,76561197970982479,30,Day of Defeat,0.1,True,2,2011
4,76561197970982479,30,Day of Defeat,0.1,True,2,2011

Mostramos información del Dataframe

In [40]:
merged_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4956176 entries, 0 to 4956175
Data columns (total 7 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   item_id             object
 2   item_name           object
 3   playtime_forever    float64
 4   recommend           bool
 5   sentiment_analysis  int64
 6   year                int64
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 231.6+ MB

Contamos los datos nulos

In [41]:
null_counts = merged_items_reviews.isnull().sum()
null_counts

user_id               0
item_id               0
item_name             0
playtime_forever      0
recommend             0
sentiment_analysis    0
year                  0
dtype: int64

Antes de hacer el merge debemos revisar el tipo de datos de la columna item_id en ambos dataframes

In [42]:
df_steam_games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32133 entries, 0 to 32132
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24062 non-null  object
 1   genres        28850 non-null  object
 2   app_name      32131 non-null  object
 3   release_date  30066 non-null  object
 4   tags          31970 non-null  object
 5   specs         31463 non-null  object
 6   price         32133 non-null  float64
 7   item_id       32133 non-null  int32
 8   developer     28834 non-null  object
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ MB

In [43]:
merged_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4956176 entries, 0 to 4956175
Data columns (total 7 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   item_id             object
 2   item_name           object
 3   playtime_forever    float64
 4   recommend           bool
 5   sentiment_analysis  int64
 6   year                int64
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 231.6+ MB

La columna item_id de merged_items_reviews es d tipo object, lo cual nos impide hacer un merge los dataframes, la trasformaremos a int

In [44]:
# Transforma la columna 'item_id' a tipo entero
merged_items_reviews['item_id'] = merged_items_reviews['item_id'].astype(int)

Uniremos el tercer Dataframes df_steam_games restante con merged_items_reviews, volveremos a utilizar el método inner para mantener la coicidencia entre ambos dataframes.

In [45]:
games_items_reviews = pd.merge(left=merged_items_reviews, right=df_steam_games, on='item_id', how='inner')

mostramos parte del Dataframe

In [46]:
games_items_reviews.head()

,user_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis,year,publisher,genres,app_name,release_date,tags,specs,price,developer
0,76561197970982479,10,Counter-Strike,0.1,True,2,2011,Valve,['Action'],Counter-Strike,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
1,76561197970982479,10,Counter-Strike,0.1,True,2,2011,Valve,['Action'],Counter-Strike,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
2,76561197970982479,10,Counter-Strike,0.1,True,2,2011,Valve,['Action'],Counter-Strike,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
3,doctr,10,Counter-Strike,1.6,True,2,2013,Valve,['Action'],Counter-Strike,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
4,doctr,10,Counter-Strike,1.6,True,2,2012,Valve,['Action'],Counter-Strike,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve

Mostramos información sobre games_items_reviews

In [47]:
games_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4358039 entries, 0 to 4358038
Data columns (total 15 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   item_id             int32
 2   item_name           object
 3   playtime_forever    float64
 4   recommend           bool
 5   sentiment_analysis  int64
 6   year                int64
 7   publisher           object
 8   genres              object
 9   app_name            object
 10  release_date        object
 11  tags                object
 12  specs               object
 13  price               float64
 14  developer           object
dtypes: bool(1), float64(2), int32(1), int64(2), object(9)
memory usage: 453.0+ MB

Contamos los datos nulos

In [48]:
null_counts = games_items_reviews.isnull().sum()
null_counts

user_id                    0
item_id                    0
item_name                  0
playtime_forever           0
recommend                  0
sentiment_analysis         0
year                       0
publisher             154731
genres                 97297
app_name                   0
release_date           90576
tags                      31
specs                  14967
price                      0
developer             112958
dtype: int64

Como ya hemos mencionado antes en este proyecto, el cliente solicito un despliegue temporal de una API que implementaremos mas adelante en un servicio web gratuito, por razones de memoria y optimización eliminaremos todos los datos nulos presentes en nuestro dataset.

In [49]:
games_items_reviews = games_items_reviews.dropna()

Visualizamos información de nuestro Dataframe

In [50]:
games_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4162762 entries, 0 to 4358031
Data columns (total 15 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   item_id             int32
 2   item_name           object
 3   playtime_forever    float64
 4   recommend           bool
 5   sentiment_analysis  int64
 6   year                int64
 7   publisher           object
 8   genres              object
 9   app_name            object
 10  release_date        object
 11  tags                object
 12  specs               object
 13  price               float64
 14  developer           object
dtypes: bool(1), float64(2), int32(1), int64(2), object(9)
memory usage: 464.5+ MB

Eliminaremos valores repetidos teniendo el siguiente criterio: un jugador puede jugar varios items o juegos, en este caso eliminaredos duplicados con respesto a user_id e item_id, es decir, vamos a eliminar los repetidos en donde exista mas de un registro con el mismo user_id y el mismo item_id. Sería incongruente mantener mas de un registro con el mismo usuario y el mismo juego.

In [51]:
games_items_reviews = games_items_reviews.drop_duplicates(subset=['user_id', 'item_id']).reset_index(drop=True)

In [52]:
games_items_reviews.tail(5)

,user_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis,year,publisher,genres,app_name,release_date,tags,specs,price,developer
1380480,76561198097165402,467910,EPΘCH,0.2,True,2,2013,Nick Everlith,"['Action', 'Adventure', 'Indie', 'RPG']",EPΘCH,2016-05-18,"['Action', 'Adventure', 'Indie', 'RPG', 'Great...","['Single-player', 'Multi-player', 'Co-op']",14.99,Nick Everlith
1380481,darrylkerrigan,319780,Airport Simulator 2015,0.7,True,2,2014,rondomedia GmbH,['Simulation'],Airport Simulator 2015,2015-04-22,"['Simulation', 'Singleplayer']","['Single-player', 'Steam Achievements']",14.99,LinkSolutions Ltd.
1380482,76561198107283457,273800,Forestry 2017 - The Simulation,0.2,True,2,0,United Independent Entertainment GmbH,['Simulation'],Forestry 2017 - The Simulation,2016-03-25,['Simulation'],"['Single-player', 'Steam Achievements', 'Parti...",19.99,"Joindots,SilentFuture"
1380483,76561198107283457,354280,ChaosTower,2.7,True,2,0,CashcowGames,"['Action', 'Casual', 'Indie', 'Simulation']",ChaosTower,2016-02-23,"['Indie', 'Casual', 'Action', 'Simulation']","['Single-player', 'Steam Achievements', 'Steam...",5.99,CashcowGames
1380484,76561198134165301,352760,Kaiju Panic,3.8,True,2,2015,Mechabit Ltd,"['Action', 'Indie', 'Strategy']",Kaiju Panic,2015-10-09,"['Action', 'Indie', 'Strategy', 'Tower Defense']","['Single-player', 'Steam Achievements', 'Full ...",9.99,Mechabit Ltd

Las columnas item_name y app_name tienen la misma información, por esa razón eliminaremos app_name

In [53]:
games_items_reviews = games_items_reviews.drop('app_name', axis=1)

In [54]:
games_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1380485 entries, 0 to 1380484
Data columns (total 14 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1380485 non-null  object
 1   item_id             1380485 non-null  int32
 2   item_name           1380485 non-null  object
 3   playtime_forever    1380485 non-null  float64
 4   recommend           1380485 non-null  bool
 5   sentiment_analysis  1380485 non-null  int64
 6   year                1380485 non-null  int64
 7   publisher           1380485 non-null  object
 8   genres              1380485 non-null  object
 9   release_date        1380485 non-null  object
 10  tags                1380485 non-null  object
 11  specs               1380485 non-null  object
 12  price               1380485 non-null  float64
 13  developer           1380485 non-null  object
dtypes: bool(1), float64(2), int32(1), int64(2), object(8)
memory usage: 133.0+ MB

In [55]:
games_items_reviews

,user_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis,year,publisher,genres,release_date,tags,specs,price,developer
0,76561197970982479,10,Counter-Strike,0.1,True,2,2011,Valve,['Action'],2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
1,doctr,10,Counter-Strike,1.6,True,2,2013,Valve,['Action'],2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
2,WeiEDKrSat,10,Counter-Strike,5.5,True,1,2013,Valve,['Action'],2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
3,death-hunter,10,Counter-Strike,104.6,True,2,2015,Valve,['Action'],2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
4,Fr0stedLine,10,Counter-Strike,9.7,True,2,0,Valve,['Action'],2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1380480,76561198097165402,467910,EPΘCH,0.2,True,2,2013,Nick Everlith,"['Action', 'Adventure', 'Indie', 'RPG']",2016-05-18,"['Action', 'Adventure', 'Indie', 'RPG', 'Great...","['Single-player', 'Multi-player', 'Co-op']",14.99,Nick Everlith
1380481,darrylkerrigan,319780,Airport Simulator 2015,0.7,True,2,2014,rondomedia GmbH,['Simulation'],2015-04-22,"['Simulation', 'Singleplayer']","['Single-player', 'Steam Achievements']",14.99,LinkSolutions Ltd.
1380482,76561198107283457,273800,Forestry 2017 - The Simulation,0.2,True,2,0,United Independent Entertainment GmbH,['Simulation'],2016-03-25,['Simulation'],"['Single-player', 'Steam Achievements', 'Parti...",19.99,"Joindots,SilentFuture"
1380483,76561198107283457,354280,ChaosTower,2.7,True,2,0,CashcowGames,"['Action', 'Casual', 'Indie', 'Simulation']",2016-02-23,"['Indie', 'Casual', 'Action', 'Simulation']","['Single-player', 'Steam Achievements', 'Steam...",5.99,CashcowGames
1380484,76561198134165301,352760,Kaiju Panic,3.8,True,2,2015,Mechabit Ltd,"['Action', 'Indie', 'Strategy']",2015-10-09,"['Action', 'Indie', 'Strategy', 'Tower Defense']","['Single-player', 'Steam Achievements', 'Full ...",9.99,Mechabit Ltd

In [56]:
games_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1380485 entries, 0 to 1380484
Data columns (total 14 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   user_id             1380485 non-null  object
 1   item_id             1380485 non-null  int32
 2   item_name           1380485 non-null  object
 3   playtime_forever    1380485 non-null  float64
 4   recommend           1380485 non-null  bool
 5   sentiment_analysis  1380485 non-null  int64
 6   year                1380485 non-null  int64
 7   publisher           1380485 non-null  object
 8   genres              1380485 non-null  object
 9   release_date        1380485 non-null  object
 10  tags                1380485 non-null  object
 11  specs               1380485 non-null  object
 12  price               1380485 non-null  float64
 13  developer           1380485 non-null  object
dtypes: bool(1), float64(2), int32(1), int64(2), object(8)
memory usage: 133.0+ MB

En el siguiente codigo vamos a tratar a la columna genres y sus valores como si fueras datos dummies, vamos a generar nuevas columnas con las categorias incluidas en la columna genres y asignarles valor binario.

In [57]:
# Usar get_dummies para crear columnas binarias para cada categoría única
df_genres = games_items_reviews['genres'].str.strip("[]").str.replace("'", "").str.get_dummies(sep=', ')

# Concatenar las nuevas columnas al DataFrame original
games_items_reviews = pd.concat([games_items_reviews, df_genres], axis=1)

Eliminaremos la columna genres ya que obviamente no las necesitamos

In [59]:
# Eliminar la columna original 'genres' si ya no la necesitas
games_items_reviews = games_items_reviews.drop('genres', axis=1)

En la siguinte líne configuramos a pandas para que muestre el dataframe con todas sus columnas

In [60]:
pd.set_option('display.max_columns', None)

In [61]:
games_items_reviews.head(10)

,user_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis,year,publisher,release_date,tags,specs,price,developer,Action,Adventure,Animation &amp; Modeling,Audio Production,Casual,Design &amp; Illustration,Early Access,Education,Free to Play,Indie,Massively Multiplayer,Photo Editing,RPG,Racing,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Web Publishing
0,76561197970982479,10,Counter-Strike,0.1,True,2,2011,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,doctr,10,Counter-Strike,1.6,True,2,2013,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,WeiEDKrSat,10,Counter-Strike,5.5,True,1,2013,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,death-hunter,10,Counter-Strike,104.6,True,2,2015,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Fr0stedLine,10,Counter-Strike,9.7,True,2,0,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,diego9031,10,Counter-Strike,2.6,True,1,0,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,jarrodtrim,10,Counter-Strike,5.6,True,2,2012,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,76561198078738103,10,Counter-Strike,0.0,True,2,0,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,UTNerd24,10,Counter-Strike,0.1,True,2,2014,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,76561198138053270,10,Counter-Strike,0.0,True,2,2014,Valve,2000-11-01,"['Action', 'FPS', 'Multiplayer', 'Shooter', 'C...","['Multi-player', 'Valve Anti-Cheat enabled']",9.99,Valve,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Las columnas tags y specs solo aportan volumen en nuestro dataset, y de hecho, hay valores que estan presentes en las columnas derivadas de genres, por eso las eliminaremos.

In [62]:
# eliminaremos las columnas tags y specs
games_items_reviews = games_items_reviews.drop('tags', axis=1)
games_items_reviews = games_items_reviews.drop('specs', axis=1)

In [63]:
games_items_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1380485 entries, 0 to 1380484
Data columns (total 32 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   user_id                    1380485 non-null  object
 1   item_id                    1380485 non-null  int32
 2   item_name                  1380485 non-null  object
 3   playtime_forever           1380485 non-null  float64
 4   recommend                  1380485 non-null  bool
 5   sentiment_analysis         1380485 non-null  int64
 6   year                       1380485 non-null  int64
 7   publisher                  1380485 non-null  object
 8   release_date               1380485 non-null  object
 9   price                      1380485 non-null  float64
 10  developer                  1380485 non-null  object
 11  Action                     1380485 non-null  int64
 12  Adventure                  1380485 non-null  int64
 13  Animation &amp; Modeling   1380485 non-null  int64
 14  Audio Production           1380485 non-null  int64
 15  Casual                     1380485 non-null  int64
 16  Design &amp; Illustration  1380485 non-null  int64
 17  Early Access               1380485 non-null  int64
 18  Education                  1380485 non-null  int64
 19  Free to Play               1380485 non-null  int64
 20  Indie                      1380485 non-null  int64
 21  Massively Multiplayer      1380485 non-null  int64
 22  Photo Editing              1380485 non-null  int64
 23  RPG                        1380485 non-null  int64
 24  Racing                     1380485 non-null  int64
 25  Simulation                 1380485 non-null  int64
 26  Software Training          1380485 non-null  int64
 27  Sports                     1380485 non-null  int64
 28  Strategy                   1380485 non-null  int64
 29  Utilities                  1380485 non-null  int64
 30  Video Production           1380485 non-null  int64
 31  Web Publishing             1380485 non-null  int64
dtypes: bool(1), float64(2), int32(1), int64(23), object(5)
memory usage: 322.6+ MB

exportamos los datos a un archivo de tipo parquet para ser eficientes con la memoria.

In [65]:
games_items_reviews.to_parquet('games.parquet', index=False)